CREATE OR REPLACE PROCEDURE SP_PERSONA_GRABAR(P_NOMBRE OUT VARCHAR2,
P_APELLIDO OUT VARCHAR2,
P_DIRECCION OUT VARCHAR2)
AS
BEGIN
INSERT INTO TB_PERSONA (NOMBRE, APELLIDO, DIRECCION) VALUES(P_NOMBRE, P_APELLIDO, P_DIRECCION);
END;